config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :patients
  resources :user_specialties
  resources :specialties
  resources :attentions
  resources :ratings
  scope :profiles do
    resources :users do
      resources :schedule_events, on: :member
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'home/index'
  root 'home#index'
  get 'home/profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attention.rb
class Attention < ApplicationRecord
  belongs_to :patient
  belongs_to :user
  belongs_to :specialty

  validates :specialty, :treatment, :symptom, presence: true

  def self.specialties_attentions(user)
    chart_data = {}
    user_specialties = user.specialties
    user_specialties.each { |ue| chart_data.merge!({ "#{ue.name}": Attention.where(user: user, specialty: ue).count })}
    chart_data
  end
end

app/controllers/attentions_controller.rb
class AttentionsController < InheritedResources::Base
  before_action :set_attention, only: [:show, :edit, :update, :destroy]

  # GET /attentions
  # GET /attentions.json
  

  def index
    #@attentions = Attention.includes(:patient).all

    if params[:rut] && !params[:rut].empty?
      
      #@attentions = Attention.all
      #@patients = Patient.where('rut= ?', params[:rut])
      @attentions = current_user.attentions.joins(:patient).where(patients:{rut:params[:rut]})
    else
      @attentions = current_user.attentions
    end
  end
  

  # GET /attentions/1
  # GET /attentions/1.json
  def show
  end

  # GET /attentions/new
  def new
    @attention = Attention.new
    @attention.patient_id = params[:patient_id]
  end

  # GET /attentions/1/edit
  def edit
  end

  # POST /attentions
  # POST /attentions.json
  def create
   
    @attention = Attention.new(attention_params)
    @attention.user_id = current_user.id
    respond_to do |format|
      if @attention.save
        format.html { redirect_to @attention, notice: 'Attention was successfully created.' }
        format.json { render :show, status: :created, location: @attention }
      else
        format.html { render :new }
        format.json { render json: @attention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attentions/1
  # PATCH/PUT /attentions/1.json
  def update
    respond_to do |format|
      if @attention.update(attention_params)
        format.html { redirect_to @attention, notice: 'Attention was successfully updated.' }
        format.json { render :show, status: :ok, location: @attention }
      else
        format.html { render :edit }
        format.json { render json: @attention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attentions/1
  # DELETE /attentions/1.json
  def destroy
    @attention.destroy
    respond_to do |format|
      format.html { redirect_to attentions_url, notice: 'Attention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attention
      @attention = Attention.find(params[:id])
    end

    def attention_params
      params.require(:attention).permit(:patient_id, :attention_id, :user_id, :therapy, :treatment, :date, :time, :symptom, :specialty_id)
    end

end

app/views/attentions/_form.html.erb
<%= form_with(model: attention, local: true) do |form| %>
  <% if attention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attention.errors.count, "error") %> prohibited this attention from being saved:</h2>

      <ul>
        <% attention.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="margen-attentions">  
  <div class="field">
    <%= form.label :patient_id, "Rut Paciente: #{@attention.patient.rut}" %>
    <%= form.text_field :patient_id, hidden: true %>
  </div>

  <div class="field">
    <%= form.label :patient_id, "Nombre Paciente: #{@attention.patient.name} #{@attention.patient.last_name}" %>
    <%= form.text_field :patient_id, hidden: true %>
  </div>

  <div class="field">
    <%= form.label :specialty_id, "Especialidad:" %>
    <%= form.collection_select :specialty_id, current_user.specialties, :id, :name, {prompt: "Seleccionar Especialidad"}, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :treatment, "Tratamiento:" %>
    <%= form.text_area :treatment %>
  </div>

  <div class="field">
    <%= form.label :date, "Fecha:" %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time, "Hora:" %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :symptom, "Síntomas:" %>
    <%= form.text_field :symptom %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Atención" %>
  </div>
<% end %>
</div>

app/views/attentions/edit.html.erb
<div class="centered">
    <h1>Editing Attention</h1>

    <%= render 'form', attention: @attention %>

    <%= link_to 'Mostrar Atención', @attention, class: "btn btn-light btn-sm ml-2" %> |
    <%= link_to 'Volver', attention_path, class: "btn btn-light btn-sm ml-2" %>
</div>

app/views/attentions/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="table1 mb-3">Atenciones</h2>

  <form class="form-inline table1 mb-4">
    <input class="form-control mr-sm-2" type="search" placeholder "Buscar por Rut" aria-label="Search" name="rut">
    <button class="btn btn-info" type="submit">Buscar</button>
  </form>

<div class = "table-responsive" id="margen-abajo1">
  <table class=" table table1">
    <thead>
      <tr>
        <th>Rut</th>
        <th>Paciente</th>
        <th>Terapeuta</th>
        <th>Especialidad</th>
        <th>Tratamiento</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Sintomas</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @attentions.each do |attention| %>
        <tr>     
          <td><%= attention.patient.rut %></td>
          <td><%= attention.patient.name + " #{attention.patient.last_name}" %></td>
          <td><%= attention.user.username %></td>
          <td><%= attention.specialty.name %></td>
          <td><%= attention.treatment %></td>
          <td><%= attention.date %></td>
          <td><%= attention.time %></td>
          <td><%= attention.symptom %></td>
          
          <td><%= link_to 'Editar', edit_attention_path(attention), class: "btn btn-light btn-sm ml-2" %></td>
          <td><%= link_to 'Borrar', attention, class: "btn btn-light btn-sm ml-2", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Nueva Atencion', new_attention_path(patient_id: attention.patient.id), class: "btn btn-light btn-sm ml-2" %></td>
          </tr>
      <% end %>
    </tbody>
    
  </table>
</div>
  <br>

  
  

app/views/attentions/new.html.erb
<div class="centered mt-3" id="margen-abajo2">
    <h2>Nueva Atención</h2>

    <%= render 'form', attention: @attention %>

    <%= link_to 'Volver', patients_path %>
</div>

app/views/attentions/show.html.erb
<div class="centered">

<p id="notice"><%= notice %></p>

<p>
  <strong>Paciente:</strong>
  <%= "#{@attention.patient.name} #{@attention.patient.last_name}" %>
</p>

<p>
  <strong>Terapeuta:</strong>
  <%= @attention.user.username %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @attention.specialty.name %>
</p>
<p>
  <strong>Sintomas:</strong>
  <%= @attention.symptom %>
</p>
<p>
  <strong>Fecha:</strong>
  <%= @attention.date %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @attention.time %>
</p>
<p>
  <strong>Tratamiento:</strong>
  <%= @attention.treatment %>
</p>





<%= link_to 'Editar Atención', edit_attention_path(@attention), class: "btn btn-light btn-sm ml-2" %> |
<%= link_to 'Volver', attentions_path, class: "btn btn-light btn-sm ml-2" %>
</div>