config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :patients
  resources :user_specialties
  resources :specialties
  resources :attentions
  resources :ratings
  scope :profiles do
    resources :users do
      resources :schedule_events, on: :member
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'home/index'
  root 'home#index'
  get 'home/profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ratings, dependent: :destroy
  has_many :user_specialties, dependent: :destroy
  has_many :specialties, through: :user_specialties
  has_many :attentions, dependent: :destroy
  has_many :schedule_events, dependent: :destroy
  after_create :welcome_user
  
  validates :username, :email, :password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(username: data['name'],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def welcome_user
    mailer = MailgunMailer.welcome_email(self)
    mailer_response = mailer.deliver_now
    mailgun_message_id = mailer_response.message_id 
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    render json: resource
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    #@pie_kinds = Bookmark.joins(:kind).group("kinds.name").count
    #@pie_users = Attention.joins(:user).group("users.therapy").count
   
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @graph1 = Attention.specialties_attentions(current_user)
    @graph2 = current_user.attentions.joins(:patient).group(:name).count
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /specialtiess
  # POST /specialtiess.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialtiess/1
  # PATCH/PUT /specialtiess/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.js
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialtiess/1
  # DELETE /specialtiess/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to specialties_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :email, :password_confirmation, specialty_ids: [])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, remote: true, id: "edit_user") do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br/>
    <%= f.text_field :username, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :specialties %><br/>
    <%= f.collection_check_boxes :specialty_ids, Specialty.all, :id, :name do |s|  %>
    <%= s.label %>
    <%= s.check_box %><br>
  <% end %>
</div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br/>
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br/>
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
<script>
    $(function () {
        var userForm = $('#user_edit')
        userForm.on("complete", function (req, res) {
            console.log(res)
        })
    })
</script>

app/views/users/edit.html.erb
<div class="centered">
    <h1>Actualización de usuario</h1>

    <%= render 'form', user: @user %>

    
    <%= link_to 'Back', home_index_path, class: "btn btn-light" %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="centered">
  <h1>Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-light" %></td>
          <td><%= link_to 'Destroy', user, method: :delete, class: "btn btn-light", data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Specialty', new_user_path, class: "btn btn-light" %>
</div>
<br>



<%= link_to 'New Specialty', new_user_path, class: "btn btn-light"%>

app/views/users/new.html.erb
<div class="centered">
    <h1>New Specialty</h1>

    <%= render 'form', specialty: @specialty %>

    <%= link_to 'Back', specialties_path %>
</div>

app/views/users/show.html.erb
<div class="centered">
    <p id="notice"><%= notice %></p>
    <p>
    <strong>Usuario: </strong>
    <%= @user.username %>
    <br>
    <strong> Email:</strong>
    <%= @user.email %>
  </p>

  

  
  <strong>Especialidades:</strong>
  <% @user.specialties.each do |specialty| %>
    <p><%= specialty.name %></p>
  <% end %>



  <%= link_to 'Lista atenciones realizadas', attentions_path, class: "btn btn-light" %> |
  <%= link_to 'Editar Usuario', edit_user_path(@user), class: "btn btn-light" %> |
  <%= link_to 'Volver', root_path, class: "btn btn-light" %>
  <br><br>
  
  
  <div class="row">
    <div class="col-md-4"><%= pie_chart @graph1, title: "Atenciones por Especialidad"%></div>
    <div class="col-md-4"><%= pie_chart @graph2, title: "Cantidad Atenciones por Paciente"%></div>
  </div>

</div>