config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :patients
  resources :user_specialties
  resources :specialties
  resources :attentions
  resources :ratings
  scope :profiles do
    resources :users do
      resources :schedule_events, on: :member
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'home/index'
  root 'home#index'
  get 'home/profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/schedules_controller.rb
class SchedulesController < InheritedResources::Base

  private

    def schedule_params
      params.require(:schedule).permit(:name, :user_id)
    end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="table2">
<%= simple_form_for([schedule.user,@schedule]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', user_schedule_path(@schedule.user, @schedule) %> |
<%= link_to 'Back', user_schedules_path(@schedule.user, @schedule) %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table2">
<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.name %></td>
        <td><%= schedule.user_id %></td>
        <td><%= link_to 'Show', user_schedule_path(schedule.user, schedule) %></td>
        <td><%= link_to 'Edit', edit_user_schedule_path(schedule.user, schedule) %></td>
        <td><%= link_to 'Destroy', user_schedule_path(schedule.user, schedule), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', user_schedules_path(schedule.user, schedule) %>

app/views/schedules/show.html.erb
<div class="table2">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @schedule.name %>
  </p>
  <div class="calendar"></div>
  <p>
    <strong>User:</strong>
    <%= @schedule.user_id %>
  </p>

  <%= link_to 'New Schedule Event', new_user_schedule_schedule_event_path(@schedule.user, @schedule) %>
  <%= link_to 'Edit', edit_user_schedule_schedule_event_path(@schedule, @schedule.user) %> |
  <%= link_to 'Back', user_schedule_schedule_event_path(@schedule.user, @schedule) %>
</div>

<div id="calendar" class="table2"> </div>
<script>
    $('#calendar').fullCalendar({events: "<%= user_schedule_schedule_events_path(schedule_id: @schedule, format: :json) %>"})
</script>