config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :patients
  resources :user_specialties
  resources :specialties
  resources :attentions
  resources :ratings
  scope :profiles do
    resources :users do
      resources :schedule_events, on: :member
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'home/index'
  root 'home#index'
  get 'home/profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_profile.html.erb
<article class="content-sec color-black border-down pt-1">
    <div class="border-down border-up pt-1 pl-4">
        <h6 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue"></i>'.html_safe, root_path %>&nbsp;&nbsp;@<%= @user.username%> | 
         <span class="text-13">&nbsp;&nbsp;<%= @user.my_tweets.count%>&nbsp;&nbsp;Tweets</span></h6>
    </div>

    <div class="">
        <div class="border-down contenedor-header" >
            <%= image_tag(@user.header_photo, class: "photo-header", style:"width:100%; height:240px;") %>
        </div>
        <div class="">
            <%= image_tag(@user.photo_url, class: "perfil_photo rounded-circle ") %>
        </div>
        <div class="">
            <% if current_user != @user %>
                <% if current_user.is_following?(@user)%>
                    <%= link_to '<i class="fas fa-minus"></i>&nbsp;&nbsp;Dejar de seguir'.html_safe, users_follow_path(@user.id), class:"rounded-pill btn btn-danger text-11 button-perfil", method: :post %>
                <% else %>
                    <%= link_to '<i class="fas fa-plus"></i>&nbsp;&nbsp;Seguir'.html_safe, users_follow_path(@user.id), class:"rounded-pill btn btn-success text-11 button-perfil", method: :post %>
                <% end %>
            <% else %>
                <%= link_to "Editar perfil", edit_user_registration_path, class: "rounded-pill btn btn-outline-info text-11 button-perfil" %>
            <% end %>
        </div>
        <div class="mt-5 pt-4 date-perfil">
            <span class="text-warning">@<%= @user.username %></span><br>
            <i class="fas fa-envelope color-gray text-13"></i><span class="color-gray text-8">&nbsp; <%= @user.email %></span><br>
            <i class="fas fa-calendar-check color-gray text-13"></i><span class="color-gray text-8">&nbsp; Miembro desde el     <%=  I18n.l(@user.created_at, format: '%A, %d de %B de %Y') %></span><br>
            <span class="color-gray text-13"><%= @followed %> Siguiendo</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="color-gray text-13"><%= @follow %> Siguidores</span>
        </div>
    </div>

    <div class="mt-4 pt-4">
        <div class="card mt-3 tab-card card-special rounded-0 border-down">
            <div class="card-header tab-card-header bg-twitter border-down rounded-0">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="one-tab" data-toggle="tab" href="#one" role="tab" aria-controls="One" aria-selected="true">Tweets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="two-tab" data-toggle="tab" href="#two" role="tab" aria-controls="Two" aria-selected="false">ReTweets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="three-tab" data-toggle="tab" href="#three" role="tab" aria-controls="Three" aria-selected="false">Me gusta</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="four-tab" data-toggle="tab" href="#four" role="tab" aria-controls="Four" aria-selected="false">Siguiendo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link color-gray" id="five-tab" data-toggle="tab" href="#five" role="tab" aria-controls="Five" aria-selected="false">Seguidores</a>
                    </li>
                </ul>
            </div>

            <div class="tab-content" id="myTabContent">
                
                <div class="tab-pane fade show active bg-twitter" id="one" role="tabpanel" aria-labelledby="one-tab">
                    <% @tweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @tweets, "Show less Tweets", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
                            <%= link_to_next_page @tweets, "Shore more Tweets", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade bg-twitter" id="two" role="tabpanel" aria-labelledby="two-tab">
                    <% @retweets.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @retweets, "Show less Tweets", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @retweets.current_page %></i>
                            <%= link_to_next_page @retweets, "Show more Tweets", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade bg-twitter" id="three" role="tabpanel" aria-labelledby="three-tab">
                    <% @likes.each do |tweet| %>
                        <%= render "shared/card_tweet", tweet: tweet %>
                    <% end %>

                    <div class="p-4">
                        <div class="text-center">
                            <%= link_to_prev_page @likes, "Show less Tweets", class: "btn btn-primary btn-sm text-11" %>
                            <i class="btn btn-light btn-sm text-13 "><%= @likes.current_page %></i>
                            <%= link_to_next_page @likes, "Show more Tweets", class:"btn btn-primary btn-sm text-11"%>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade bg-twitter" id="four" role="tabpanel" aria-labelledby="four-tab">
                    <% @following.each do |user| %>
                    <article class="twitter-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope color-gray text-13"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                                <%= link_to (@user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (@user.is_following?(user) ? "Dejar de Seguir" : "Seguir"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>

                <div class="tab-pane fade bg-twitter" id="five" role="tabpanel" aria-labelledby="five-tab">
                     <% @follower.each do |user| %>
                    <article class="twitter-post py-3"> 
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-1">
                                <%= link_to (image_tag (user.photo_url), 
                                    class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                                    tweet_detail_path(user)
                                %>
                            </div>
                            <div class="col-3">
                                <span class="text-warning text-13">@<%= user.username.capitalize %></span>
                            </div>
                            <div class="col-5">
                                <span class="color-gray text-13"><i class="fas fa-envelope"></i>&nbsp;&nbsp;&nbsp;<%= user.email %></span>
                            </div>
                            <div class="col-2">
                            <% if current_user != user%>
                                <%= link_to (@user.is_following?(user) ? "<i class='fas fa-user-minus text-warning text-13'></i>" : "<i class='fas fa-user-plus color-blue-deep text-13'></i>").html_safe, 
                                    users_follow_path(user.id), 
                                    class: "follow-btn",
                                    'title' => (@user.is_following?(user) ? "Stop Following" : "Follow"),
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'right',
                                    method: :post
                                %>
                            <% end %>
                            </div>
                        </div>
                    </article>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</article>

app/views/shared/_card_tweet.html.erb
<article class="mytwitter-post py-3">
    <% if tweet.is_retweet?%>
    <div class="row justify-content-md-center">
        <div class="det-post-row">
            <div class="row justify-content-center">
                <div class="col-7 pl-1">
                    <i class="fas fa-retweet color-tiara text-8"></i> <%=  link_to "#{tweet.user.username} ReTweet", tweet.tweet_ref, class:"color-tiara text-decoration-none text-8" %>
                    &nbsp;&nbsp;&nbsp;
                    <span class="text-11 color-tiara"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet), class: "color-tiara text-decoration-none" %></span>
                </div>
            </div>

            <div class="row mx-4 px-4">
                <div class="col- px-3">
                    <div class="mb-1">
                        <%= link_to (image_tag (tweet.tweet_ref.user.photo_url), 
                            class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                            tweet_detail_path(tweet.tweet_ref.user)
                        %>
                    </div>
                    <% if user_signed_in? && current_user != tweet.user %>
                        <div class="text-center">
                            <%= link_to (current_user.is_following?(tweet.user) ? "<i class='fas fa-user-minus color-tiara ml-1 text-8'></i>" : "<i class='fas fa-user-plus color-danube ml-1 text-8'></i>").html_safe, 
                                users_follow_path(tweet.user.id), 
                                class: "follow-btn",
                                'title' => (current_user.is_following?(tweet.user) ? "Dejar de Seguir" : "Seguir"),
                                'data-toggle' => 'tooltip',
                                'data-placement' => 'right',
                                method: :post
                            %>
                        </div>
                    <% end %>
                </div>

                <div class="col-10">
                    <div>
                        <i class="text-13 text-warning"><strong>@<%= tweet.tweet_ref.user.username.capitalize %></strong></i>
                        &nbsp;&nbsp;&nbsp;
                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.tweet_ref.user.created_at), tweet_path(tweet.tweet_ref), class: "color-time text-decoration-none" %></span>
                    </div>
                    <div class="text-11 border-down-white pb-2">
                        <span class="body-content">&nbsp;&nbsp;&nbsp;<%= tweet.content.html_safe %></span>
                    </div>

                    <div class="text-11 div-like-retweet pt-1">
                        <div class="row">
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post,
                                            class: "tooltips text-warning", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Like" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post, 
                                            class: "text-white tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Like" }
                                        %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>

                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: "text-white text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Re-Wispear" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: " text-warning text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Re-Wispear" }%>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <% else %>
  
            
    <div class="row justify-content-md-center">
        <div class="det-post-row">
            <div class="row mx-4 px-4">
                <div class="col- px-3">
                    <div class="mb-1">
                        <%= link_to (image_tag (tweet.user.photo_url), 
                            class: 'photo-avatar-post rounded-circle', alt: "Avatar Post"), 
                            tweet_detail_path(tweet.user_id)
                        %>
                    </div>
                    <% if user_signed_in? && current_user != tweet.user %>
                        <div class="text-center ">
                            <%= link_to (current_user.is_following?(tweet.user) ? "<i class='fas fa-user-minus color-tiara ml-1 text-8'></i>" : "<i class='fas fa-user-plus color-danube ml-1 text-8'></i>").html_safe, 
                                users_follow_path(tweet.user.id), 
                                class: "follow-btn",
                                'title' => (current_user.is_following?(tweet.user) ? "Dejar de Seguir" : "Seguir"),
                                'data-toggle' => 'tooltip',
                                'data-placement' => 'right',
                                method: :post
                            %>
                        </div>
                    <% end %>
                </div>

                <div class="col-10">
                    <div>
                        <i class="text-13 text-warning"><strong>@<%= tweet.user.username.capitalize %></strong></i>
                        &nbsp;&nbsp;&nbsp;
                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet_path(tweet), class: "color-time text-decoration-none" %></span>
                    </div>
                    <div class="text-11 border-down-white pb-2">
                        <span class="body-content">&nbsp;&nbsp;&nbsp;<%= tweet.content.html_safe %></span>
                    </div>

                    <div class="text-11 div-like-retweet pt-1">
                        <div class="row">
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post,
                                            class: "tooltips text-warning", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Like" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, 
                                            tweet_likes_path(tweet), 
                                            method: :post, 
                                            class: "text-white tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Like" }
                                        %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>

                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: "text-white text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Re-Wispear" }
                                        %>
                                    <% else %>
                                        <%= link_to '<i class="fas fa-retweet"></i>'.html_safe, 
                                            tweet_retweet_path(tweet), 
                                            method: :post, 
                                            class: " text-warning text-decoration-none tooltips", 
                                            title: '', 
                                            data: { toggle: 'tooltip', placement: 'top', original_title: "Quitar Re-Wispear" }%>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <% end %>
</article>

app/views/shared/_footer.html.erb
<footer class="footer fixed-bottom shadow-lg mt-5">
    <div class="row justify-content-center align-items-center text-black">
        <div class="col-7 p-1">
            <p class="">Todos los derechos reservados, <strong>Therapy Spa</strong>
            <br>
            <i class="">Contáctanos: +56-987654321</i>
            <a href="mailto:info@therapymgr.com?Subject=Solicitud%de%informacion">info@therapymgr.com</a>
            </p>
        </div>
        
    </div>
</footer>

app/views/shared/_footer2.html.erb
<footer class="footer2 fixed-bottom shadow-lg mt-5">
    <div class="row justify-content-center align-items-center text-black">
        <div class="col-7 p-1">
            <p class="">Todos los derechos reservados, <strong>Therapy Spa</strong>
            <br>
            <i class="">Contáctanos: +56-987654321</i>
            <a href="mailto:info@therapymgr.com?Subject=Solicitud%de%informacion">info@therapymgr.com</a>
            </p>
        </div>
        
    </div>
</footer>

app/views/shared/_left_side.html.erb
<nav class="left-side">

<% if user_signed_in? %>


<!--Row Icon Twitter-->
    
    <!--Row Home-->
    <div class="row text-white mt-0 ">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-house-damage fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
      <p><strong><%= link_to "Home", root_path, class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>
    
    <!--Row My Profile-->
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-user fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
          <p><strong><%= link_to "Mi Perfil", user_path(current_user), class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>
    
    

    <!--Row Patients-->
    <div class="row text-white mt-0 ">
      <div class="col-4 text-right pr-0">
        <i class="far fa-dot-circle fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
      <p><strong><%= link_to "Pacientes", patients_path, class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>

    <!--Row Agenda Appointments-->
    <div class="row text-white mt-0 ">
      <div class="col-4 text-right pr-0">
        <i class="far fa-dot-circle fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
      <p><strong><%= link_to "Agenda", user_schedule_events_path(current_user), class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>


    <!--Row Attentions-->
    <div class="row text-white mt-0 ">
      <div class="col-4 text-right pr-0">
        <i class="far fa-dot-circle fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
      <p><strong><%= link_to "Atenciones", attentions_path, class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>
    
    <!--Row Specialty-->
    <% if current_user.admin %>
      <div class="row text-white mt-0 ">
        <div class="col-4 text-right pr-0">
          <i class="far fa-dot-circle fa-sm color-blue"></i>
        </div>
        <div class="col-5 color-gray menu-left">
          <p><strong><%= link_to "Especialidades", specialties_path, class: "fas text-decoration-none color-gray"%></strong></p>
        </div>
      </div>
    <% end %>
    

    
    <% if current_user.admin %>       
      <div class="row text-white mt-0">
        <div class="col-4 text-right pr-0">
          <i class="fas fa-user-shield fa-sm color-blue"></i>
        </div>
        <div class="col-5 color-gray menu-left">
          <p><strong><%= link_to "Panel Administracion", admin_users_path, class: "fas text-decoration-none color-gray"%></strong></p>
        </div>
      </div>
              
    <% end %>

    <!--Row Ratings-->
    <div class="row text-white mt-0 ">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-star fa-sm color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
      <p><strong><%= link_to "Calificar App", ratings_path, class: "fas text-decoration-none color-gray"%></strong></p>
      </div>
    </div>

    <!--Row Close session-->
    <div class="row text-white mt-0">
      <div class="col-4 text-right pr-0">
        <i class="fas fa-sign-out-alt color-blue"></i>
      </div>
      <div class="col-5 color-gray menu-left">
        <%= link_to "  Cerrar Sesion", destroy_user_session_path, method: :delete ,class:"fas text-center font-weight-bolder border-white text-white text-13"%>
      </div>
    </div>
    
<% else %>
  <div class="row text-white mt-0">
    <div class="col-2 text-right pr-0">
      <i class="fas fa-hands-helping fa-sm color-blue"></i>
    </div>
    <div class="col-5 color-gray menu-left">
      <p><strong>Qué es ?</strong></p>
    </div>
  </div>

  <div class="row text-white mt-0">
    <div class="col-12 color-gray menu-left">
      <p class="left-space">Es una aplicación que permite a los profesionales de terapias naturales administrar las sesiones de sus pacientes, teniendo al alcance su historial, terapias aplicadas, entre otros, permitiendo entregar la mejor experiencia de atención</p>
    </div>
  </div>
<br>
  <div class="row text-white mt-0">
    <div class="col-2 text-right pr-0">
      <i class="fas fa-toolbox fa-sm color-blue"></i>
    </div>
    <div class="col-8 color-gray menu-left">
      <p><strong>Principales Funciones</strong></p>
    </div>
  </div>

  <div class="row text-white mt-0">
    <div class="col-12 color-gray menu-left">
      <p class="left-space">Creación de perfil de pacientes</p>
    </div>
    <div class="col-12 color-gray menu-left">
      <p class="left-space">Registro de atenciones de pacientes y detalles</p>
    </div>
    <div class="col-12 color-gray menu-left">
      <p class="left-space">Agendar sesiones para pacientes existentes</p>
    </div>
    <div class="col-12 color-gray menu-left">
      <p class="left-space">Graficos de distribucion de atenciones</p>
    </div>
  </div>
<% end %>
</nav>

app/views/shared/_messages.html.erb
<div class="msg-format pt-4 text-11">
    <% if alert.present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <i class="fas fa-exclamation-triangle fa-sm"></i>&nbsp;<strong>Alerta :</strong><i class="alert text-left"><%= alert %></i>
            <button type="button" class="close text-13" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>   
    <% elsif notice.present? %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <i class="fas fa-flag fa-sm"></i>&nbsp;<i class="alert text-left"><%= notice %></i>
            <button type="button" class="close text-13" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-color">
  
  <a class="navbar-brand font-weight-bold cool-link" href="..">Therapy Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <% unless user_signed_in? %>
        
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to 'Inicia Sesión', new_user_session_path, class: "btn btn-light" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Regístrate', new_user_registration_path, class: "btn btn-light ml-2" %>
            </li>
        </ul>
    <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_right_side.html.erb
<nav class="right-side">
    
    <% if user_signed_in? %>
        <div class="mt-4 mb-5">
            <div class="row justify-content-center">
                <div class="col-8">
                    <%if user_signed_in? %>
                        <p></p>
                    <% end %>
                </div>
            </div>
        </div>
    <% else %>
        <div class="row text-white mt-0">
            
            <div class="col-10 color-gray menu-center">
                <p class="left-space"><strong>Qué esperas para vivir la experiencia<br> Therapy Manager ?. Crea tu usuario</strong></p>
                <%= link_to 'AQUI', new_user_registration_path, class: "btn btn-light ml-5" %>
            </div>
            <div class="col-10 color-gray menu-center mt-4 left-space">
                <p><strong>Valoración:</strong></p>
                <i class="fas fa-star fa-lg" style="color:yellow"></i>
                
                
                <%= @rating_promedio %>
            </div>
           
        
      </div>
            
        </div>
    <% end %>

    

</nav>